repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: duckdb-format
        name: duckdb format
        entry: python3 duckdb/scripts/format.py --all --fix --noconfirm --directories src test
        language: system
        pass_filenames: false
